$(function(){
    var dom01=$("<a href='unvr.html'><img class='bnnr' src='UNVR.PNG' alt='±§Ãè²Ê³Ø' /></a>")
    var dom02=$("<a href='lfsc.html'><img class='bnnr' src='LFSC.PNG' alt='À¸Ì¿²Ê³Ø' /></a>")
    var dom03=$("<a href='nrsc.html'><img class='bnnr' src='NRSC.PNG' alt='¿À·Ğ²Ê³Ø' /></a>")
    var dom04=$("<a href='infm.html'><img class='bnnr' src='INFM.PNG' alt='¾ğÊó²Ê³Ø' /></a>")
    var dom05=$("<a href='intl.html'><img class='bnnr' src='INTL.PNG' alt='ÃÎÇ½²Ê³Ø' /></a>")
    var dom06=$("<a href='cmmn.html'><img class='bnnr' src='CMMN.PNG' alt='ÄÌ¿®²Ê³Ø' /></a>")
    var dom07=$("<a href='mthm.html'><img class='bnnr' src='MTHM.PNG' alt='¿ôÍı²Ê³Ø' /></a>")
    var dom08=$("<a href='mtrl.html'><img class='bnnr' src='MTRL.PNG' alt='Êª¼Á²Ê³Ø' /></a>")
    var dom09=$("<a href='fldd.html'><img class='bnnr' src='FLDD.PNG' alt='Î®ÂÎ²Ê³Ø' /></a>")
    var dom10=$("<a href='ecnm.html'><img class='bnnr' src='ECNM.PNG' alt='·ĞºÑ²Ê³Ø' /></a>")
    var dom11=$("<a href='dsgn.html'><img class='bnnr' src='DSGN.PNG' alt='Àß·×²Ê³Ø' /></a>")
    var dom12=$("<a href='lngg.html'><img class='bnnr' src='LNGG.PNG' alt='¸À¸ì²Ê³Ø' /></a>")
    var dom13=$("<a href='hmnb.html'><img class='bnnr' src='HMNB.PNG' alt='¿Í´Ö²Ê³Ø' /></a>")
    var dom14=$("<a href='aeth.html'><img class='bnnr' src='AETH.PNG' alt='Èş½Ñ²Ê³Ø' /></a>")
    var dom15=$("<a href='lgcl.html'><img class='bnnr' src='LGCL.PNG' alt='ÏÀÍı²Ê³Ø' /></a>")
    var dom16=$("<a href='ckng.html'><img class='bnnr' src='CKNG.PNG' alt='Ä´Íı²Ê³Ø' /></a>")
    var dom17=$("<a href='bhvr.html'><img class='bnnr' src='BHVR.PNG' alt='¹ÔÆ°²Ê³Ø' /></a>")
    var dom18=$("<a href='hrmn.html'><img class='bnnr' src='HRMN.PNG' alt='Ä´ÏÂ²Ê³Ø' /></a>")
    var dom19=$("<a href='gnrt.html'><img class='bnnr' src='GNRT.PNG' alt='È¯ÅÅ²Ê³Ø' /></a>")
    var dom20=$("<a href='fddr.html'><img class='bnnr' src='FDDR.PNG' alt='¿©ºà²Ê³Ø' /></a>")
    var dom21=$("<a href='nvst.html'><img class='bnnr' src='NVST.PNG' alt='Åê»ñ²Ê³Ø' /></a>")
    var dom22=$("<a href='mchn.html'><img class='bnnr' src='MCHN.PNG' alt='µ¡³£²Ê³Ø' /></a>")
    var dom23=$("<a href='ntrr.html'><img class='bnnr' src='NTRR.PNG' alt='²ÈÁõ²Ê³Ø' /></a>")
    var dom24=$("<a href='frmt.html'><img class='bnnr' src='FRMT.PNG' alt='·ÁÂÖ²Ê³Ø' /></a>")
    var dom25=$("<a href='fshn.html'><img class='bnnr' src='FSHN.PNG' alt='Éş¾ş²Ê³Ø' /></a>")
    var dom26=$("<a href='grcl.html'><img class='bnnr' src='GRCL.PNG' alt='¿¢ÇÀ²Ê³Ø' /></a>")
    var dom27=$("<a href='lgst.html'><img class='bnnr' src='LGST.PNG' alt='ÊªÎ®²Ê³Ø' /></a>")
    var dom28=$("<a href='prsv.html'><img class='bnnr' src='PRSV.PNG' alt='ÊİÂ¸²Ê³Ø' /></a>")
    var dom29=$("<a href='mtsc.html'><img class='bnnr' src='MTSC.PNG' alt='·Á¼©²Ê³Ø' /></a>")
    var dom30=$("<a href='cryp.html'><img class='bnnr' src='CRYP.PNG' alt='°Å¹æ²Ê³Ø' /></a>")
    var dom31=$("<a href='svng.html'><img class='bnnr' src='SVNG.PNG' alt='ÀáÌó²Ê³Ø' /></a>")
    var dom32=$("<a href='lwrl.html'><img class='bnnr' src='LWRL.PNG' alt='Ë¡Â§²Ê³Ø' /></a>")
    var dom33=$("<a href='ctst.html'><img class='bnnr' src='CTST.PNG' alt='Êø²õ²Ê³Ø' /></a>")
    var dom34=$("<a href='oprt.html'><img class='bnnr' src='OPRT.PNG' alt='±é»»²Ê³Ø' /></a>")
    var dom35=$("<a href='nfln.html'><img class='bnnr' src='NFLN.PNG' alt='±Æ¶Á²Ê³Ø' /></a>")
    var dom36=$("<a href='crtq.html'><img class='bnnr' src='CRTQ.PNG' alt='ºÛÈ½²Ê³Ø' /></a>")
    var dom37=$("<a href='mstk.html'><img class='bnnr' src='MSTK.PNG' alt='µ¶¸í²Ê³Ø' /></a>")
    var dom38=$("<a href='bury.html'><img class='bnnr' src='BURY.PNG' alt='¸ÅÊ¯²Ê³Ø' /></a>")
    var dom39=$("<a href='phnm.html'><img class='bnnr' src='PHNM.PNG' alt='²»ÁÛ²Ê³Ø' /></a>")
    var dom40=$("<a href='strt.html'><img class='bnnr' src='STRT.PNG' alt='³¹Ï©²Ê³Ø' /></a>")
    var dom41=$("<a href='hlth.html'><img class='bnnr' src='HLTH.PNG' alt='·ò¹¯²Ê³Ø' /></a>")
    var dom42=$("<a href='slsm.html'><img class='bnnr' src='SLSM.PNG' alt='±Ä¶È²Ê³Ø' /></a>")
    var dom43=$("<a href='dcsn.html'><img class='bnnr' src='DCSN.PNG' alt='·èÄê²Ê³Ø' /></a>")
    var dom44=$("<a href='slpt.html'><img class='bnnr' src='SLPT.PNG' alt='¿çÌ²²Ê³Ø' /></a>")
    var dom45=$("<a href='cncn.html'><img class='bnnr' src='CNCN.PNG' alt='½¸Ãæ²Ê³Ø' /></a>")
    var dom46=$("<a href='stps.html'><img class='bnnr' src='STPS.PNG' alt='ÃÊ³¬²Ê³Ø' /></a>")
    var dom47=$("<a href='prcs.html'><img class='bnnr' src='PRCS.PNG' alt='²áÄø²Ê³Ø' /></a>")
    var dom48=$("<a href='ftge.html'><img class='bnnr' src='FTGE.PNG' alt='ÈèÏ«²Ê³Ø' /></a>")
    var dom49=$("<a href='clbt.html'><img class='bnnr' src='CLBT.PNG' alt='³Ê¹¥²Ê³Ø' /></a>")
    var dom50=$("<a href='grtt.html'><img class='bnnr' src='GRTT.PNG' alt='´¶¼Õ²Ê³Ø' /></a>")
    var dom51=$("<a href='hmrs.html'><img class='bnnr' src='HMRS.PNG' alt='ëßëâ²Ê³Ø' /></a>")
    var dom52=$("<a href='rcvr.html'><img class='bnnr' src='RCVR.PNG' alt='²óÉü²Ê³Ø' /></a>")
    var dom53=$("<a href='prdc.html'><img class='bnnr' src='PRDC.PNG' alt='Í½Â¬²Ê³Ø' /></a>")
    var dom54=$("<a href='abnd.html'><img class='bnnr' src='ABND.PNG' alt='»¦³²²Ê³Ø' /></a>")
    var dom55=$("<a href='pbsh.html'><img class='bnnr' src='PBSH.PNG' alt='½ĞÈÇ²Ê³Ø' /></a>")
    var dom56=$("<a href='trns.html'><img class='bnnr' src='TRNS.PNG' alt='ËİÌõ²Ê³Ø' /></a>")
    var dom57=$("<a href='insp.html'><img class='bnnr' src='INSP.PNG' alt='Îî´¶²Ê³Ø' /></a>")
    var dom58=$("<a href='rasn.html'><img class='bnnr' src='RASN.PNG' alt='Íı¶ş²Ê³Ø' /></a>")
    var dom59=$("<a href='brng.html'><img class='bnnr' src='BRNG.PNG' alt='Âà¶ş²Ê³Ø' /></a>")
    var dom60=$("<a href='impr.html'><img class='bnnr' src='IMPR.PNG' alt='°õ¾İ²Ê³Ø' /></a>")
    var dom61=$("<a href='lght.html'><img class='bnnr' src='LGHT.PNG' alt='î¨¾Ğ²Ê³Ø' /></a>")
    var dom62=$("<a href='bndn.html'><img class='bnnr' src='BNDN.PNG' alt='°ø±ï²Ê³Ø' /></a>")
    var dom63=$("<a href='tlnt.html'><img class='bnnr' src='TLNT.PNG' alt='ºÍÇ½²Ê³Ø' /></a>")
    var dom64=$("<a href='qstn.html'><img class='bnnr' src='QSTN.PNG' alt='ÌäÅú²Ê³Ø' /></a>")
    var dom65=$("<a href='mthd.html'><img class='bnnr' src='MTHD.PNG' alt='ÊıË¡²Ê³Ø' /></a>")
    var dom66=$("<a href='vlbl.html'><img class='bnnr' src='VLBL.PNG' alt='²ÁÃÍ²Ê³Ø' /></a>")
    var dom67=$("<a href='psyc.html'><img class='bnnr' src='PSYC.PNG' alt='¿´°ø²Ê³Ø' /></a>")
    var dom68=$("<a href='atms.html'><img class='bnnr' src='ATMS.PNG' alt='Ê·µ¤²Ê³Ø' /></a>")
    var dom69=$("<a href='styl.html'><img class='bnnr' src='STYL.PNG' alt='ÂÎ·¿²Ê³Ø' /></a>")
    var dom70=$("<a href='fnrl.html'><img class='bnnr' src='FNRL.PNG' alt='ÁòÁ÷²Ê³Ø' /></a>")

    $("#nav").append(dom01).append(dom02).append(dom03).append(dom04).append(dom05).append(dom06).append(dom07)  
    $("#nav").append(dom08).append(dom09).append(dom10).append(dom11).append(dom12).append(dom13).append(dom14)  
    $("#nav").append(dom15).append(dom16).append(dom17).append(dom18).append(dom19).append(dom20).append(dom21)
    $("#nav").append(dom22).append(dom23).append(dom24).append(dom25).append(dom26).append(dom27).append(dom28)
    $("#nav").append(dom29).append(dom30).append(dom31).append(dom32).append(dom33).append(dom34).append(dom35)
    $("#nav").append(dom36).append(dom37).append(dom38).append(dom39).append(dom40).append(dom41).append(dom42)
    $("#nav").append(dom43).append(dom44).append(dom45).append(dom46).append(dom47).append(dom48).append(dom49)
    $("#nav").append(dom50).append(dom51).append(dom52).append(dom53).append(dom54).append(dom55).append(dom56)
    $("#nav").append(dom57).append(dom58).append(dom59).append(dom60).append(dom61).append(dom62).append(dom63)
    $("#nav").append(dom64).append(dom65).append(dom66).append(dom67).append(dom68).append(dom69).append(dom70)
})
